### PR TITLE
zwx: mindmap-jump-note-editor

### LINKED ISSUE #144: 路书编辑器，查看文献笔记，跳转编辑文献笔记页面

### PR DESCRIPTION
**Pull request by zwx980624**
close #144

### CODE REVIEW

**Review by luo-junyu — APPROVED** [review]
NO PROBLEM!

**Comment by luo-junyu** [comment]
Please Resolve the conflicts in the code~

**Comment by zwx980624** [comment]
> Please Resolve the conflicts in the code~

already solved

**Comment by luo-junyu** [comment]
ok GREAT!

**Comment by luo-junyu** [comment]
It seems something wrong wrong

**Pull request merged**
